"""
Report Generator for HackerAI Framework
"""

import json
import csv
import os
from pathlib import Path
from datetime import datetime
from typing import Dict, List, Any

class ReportGenerator:
    """
    Generate reports in various formats
    """
    
    def __init__(self, output_dir: str = "output/reports"):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)
    
    def generate_html_report(self, data: Dict, filename: str = None) -> str:
        """Generate HTML report"""
        if not filename:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            filename = f"report_{timestamp}.html"
        
        filepath = self.output_dir / filename
        
        html_content = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <title>HackerAI Report</title>
            <style>
                body {{ font-family: Arial, sans-serif; margin: 40px; }}
                .header {{ background: #2c3e50; color: white; padding: 20px; border-radius: 5px; }}
                .section {{ margin: 20px 0; padding: 15px; border-left: 4px solid #3498db; background: #f8f9fa; }}
                .vuln {{ background: #fff3cd; border: 1px solid #ffeaa7; padding: 10px; margin: 5px 0; }}
                .critical {{ border-color: #e74c3c; }}
                .high {{ border-color: #e67e22; }}
                .medium {{ border-color: #f39c12; }}
                .low {{ border-color: #27ae60; }}
                table {{ width: 100%; border-collapse: collapse; margin: 10px 0; }}
                th, td {{ padding: 8px; text-align: left; border-bottom: 1px solid #ddd; }}
                th {{ background-color: #f2f2f2; }}
            </style>
        </head>
        <body>
            <div class="header">
                <h1>🔍 HackerAI Security Report</h1>
                <p>Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
            </div>
        """
        
        # Add target info
        if 'target' in data:
            html_content += f"""
            <div class="section">
                <h2>🎯 Target Information</h2>
                <p><strong>Target:</strong> {data.get('target', 'N/A')}</p>
                <p><strong>Scan Date:</strong> {data.get('timestamp', datetime.now().strftime('%Y-%m-%d %H:%M:%S'))}</p>
            </div>
            """
        
        # Add vulnerabilities
        if 'vulnerabilities' in data and data['vulnerabilities']:
            html_content += """
            <div class="section">
                <h2>⚠️ Vulnerabilities Found</h2>
            """
            
            for vuln in data['vulnerabilities']:
                severity = vuln.get('severity', 'info').lower()
                html_content += f"""
                <div class="vuln {severity}">
                    <h3>{vuln.get('type', 'Unknown')} - {severity.upper()}</h3>
                    <p><strong>Description:</strong> {vuln.get('description', 'No description')}</p>
                    <p><strong>Recommendation:</strong> {vuln.get('recommendation', 'No recommendation')}</p>
                </div>
                """
            
            html_content += "</div>"
        
        # Add scan results
        if 'data' in data:
            html_content += """
            <div class="section">
                <h2>📊 Scan Results</h2>
                <table>
                    <tr><th>Key</th><th>Value</th></tr>
            """
            
            for key, value in data['data'].items():
                if isinstance(value, list):
                    value = ', '.join(str(v) for v in value[:5])
                    if len(data['data'][key]) > 5:
                        value += f" ... and {len(data['data'][key]) - 5} more"
                html_content += f"<tr><td>{key}</td><td>{value}</td></tr>"
            
            html_content += """
                </table>
            </div>
            """
        
        html_content += """
            <div class="section">
                <p><em>Report generated by HackerAI Framework</em></p>
            </div>
        </body>
        </html>
        """
        
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(html_content)
        
        return str(filepath)
    
    def generate_json_report(self, data: Dict, filename: str = None) -> str:
        """Generate JSON report"""
        if not filename:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            filename = f"report_{timestamp}.json"
        
        filepath = self.output_dir / filename
        
        # Add metadata
        report_data = {
            "metadata": {
                "generated_at": datetime.now().isoformat(),
                "tool": "HackerAI Framework",
                "version": "4.0.0"
            },
            "data": data
        }
        
        with open(filepath, 'w', encoding='utf-8') as f:
            json.dump(report_data, f, indent=2, default=str)
        
        return str(filepath)
    
    def generate_csv_report(self, data: Dict, filename: str = None) -> str:
        """Generate CSV report"""
        if not filename:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            filename = f"report_{timestamp}.csv"
        
        filepath = self.output_dir / filename
        
        with open(filepath, 'w', newline='', encoding='utf-8') as f:
            writer = csv.writer(f)
            
            # Write header
            writer.writerow(['Field', 'Value'])
            
            # Write basic info
            if 'target' in data:
                writer.writerow(['Target', data['target']])
            
            writer.writerow(['Status', data.get('status', 'unknown')])
            writer.writerow(['Message', data.get('message', '')])
            writer.writerow(['Timestamp', data.get('timestamp', datetime.now().isoformat())])
            
            # Write vulnerabilities
            if 'vulnerabilities' in data and data['vulnerabilities']:
                writer.writerow([])
                writer.writerow(['Vulnerabilities'])
                writer.writerow(['Type', 'Severity', 'Description', 'Recommendation'])
                
                for vuln in data['vulnerabilities']:
                    writer.writerow([
                        vuln.get('type', ''),
                        vuln.get('severity', ''),
                        vuln.get('description', ''),
                        vuln.get('recommendation', '')
                    ])
        
        return str(filepath)
    
    def generate_markdown_report(self, data: Dict, filename: str = None) -> str:
        """Generate Markdown report"""
        if not filename:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            filename = f"report_{timestamp}.md"
        
        filepath = self.output_dir / filename
        
        markdown = f"""# HackerAI Security Report
        
## Target Information
- **Target**: {data.get('target', 'N/A')}
- **Scan Date**: {data.get('timestamp', datetime.now().strftime('%Y-%m-%d %H:%M:%S'))}
- **Status**: {data.get('status', 'unknown')}

## Results
{data.get('message', 'No message')}

"""
        
        # Add vulnerabilities
        if 'vulnerabilities' in data and data['vulnerabilities']:
            markdown += "## Vulnerabilities Found\n\n"
            
            for vuln in data['vulnerabilities']:
                severity = vuln.get('severity', 'info').upper()
                markdown += f"### {vuln.get('type', 'Unknown')} ({severity})\n"
                markdown += f"- **Description**: {vuln.get('description', 'No description')}\n"
                markdown += f"- **Recommendation**: {vuln.get('recommendation', 'No recommendation')}\n\n"
        
        # Add data
        if 'data' in data and data['data']:
            markdown += "## Scan Data\n\n"
            
            for key, value in data['data'].items():
                if isinstance(value, list):
                    value = ', '.join(str(v) for v in value[:3])
                    if len(data['data'][key]) > 3:
                        value += f" ... and {len(data['data'][key]) - 3} more"
                markdown += f"- **{key}**: {value}\n"
        
        markdown += f"\n---\n*Report generated by HackerAI Framework on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*"
        
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(markdown)
        
        return str(filepath)


# Singleton instance
_report_generator = None

def get_report_generator() -> ReportGenerator:
    """Get report generator instance"""
    global _report_generator
    if _report_generator is None:
        _report_generator = ReportGenerator()
    return _report_generator
